# Generated by Django 5.0.6 on 2024-05-24 15:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 24, 15, 5, 26, 977315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
