# Generated by Django 5.0.6 on 2024-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_auth', '0002_auth_created_auth_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_tracks', to='music_auth.favorite'),
        ),
    ]
