# Generated by Django 5.0.6 on 2024-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_auth', '0003_alter_track_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
