# Generated by Django 5.0.6 on 2024-05-26 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_auth', '0004_alter_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 0, 59, 29, 724392, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
